### ISSUE TITLE
Other commits from lazVTV

### ISSUE THREAD

**Issue by salvadorbs** [salvadorbs/VirtualTreeView-Lazarus#9]
- [x] [VTV: fix getting handle when not yet shown. Issue](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/641a76447bb38439bd6340f7b1d4477c765b634d) [#40791](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40791) 
- [x] [VirtualTreeView: Improved LCL scaling.](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/402cffbdfd50f7d99f79fefcf79c8ae317bd5c79)
- [ ] [VirtualTreeView: Improve Advanced sample project ](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/76d430baad35be5a319abf69e2021f446c4229bb)
- [ ] [VirtualTreeView: Fix memory leaks in Advanced demo ](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/3c2da22f5246d8f5cedba2e848224e3371435a81)
- [x] [VirtualTreeView: Fix header paint issue in gtk2.](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/8b9b6cd85d28fa7ef10f1952179dacdeb2fda5ba)
- [x] [VirtualTreeView: Fix painting of unthemed expland/collapse buttons in non-Windows widgetsets.](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/d5040729dfbea138643b21890e8c13f141f6090a)
- [ ] [Examples/VirtualTreeViews: Improved rendering of AdvancedDemo in dark mode.](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/4e6afdc699d5d76b5f7e83e0ea113c45679885a8)
- [x] [Laz.VirtualTreeView: improve paint for cocoa](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/cb239c1222df8971299cbdca3a12b1d801164bbb)
- [ ] [VirtualTreeView: Add dataarray sample project.](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/92271f5b1ac6c0dd393dec32532a549a6117d636)

**Comment by salvadorbs** [comment]
- [x] [virtualtreeview: partially revert 402cffbd issue #41210 ](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/a775e7be7cc40276bcc75d7d36b968c18374ee09)

**Comment by salvadorbs** [comment]
- [x] [LCL: SetDeviceScaleRatio renamed to SetCanvasScaleFactor.](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/34844aa9340f1dbe874a52ba1d01823bdc87c189)
- [x] [VirtualTreeViews: Fix crash due to incorrectly named cursor resources.](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/99b6e9551a0e7c23b15d9e4fccb2c1cc19205ae7)
- [x] [LazVirtualTrees: removed cocoa workaround from PaintHeader. related to the issue ](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/ff108ae5b634285276162974eb08e13c9b6a91a2)[#41313](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/41313)
- [x] [TLazVirtualTrees: removed cocoa workarounds. Related to the issue ](https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/4d840c6866c1fd0253031fa658baf4029e46ca21)[#41313](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/41313)
